### PR TITLE
Fixed nm full path

### PR DESCRIPTION
**Pull request by daizeng1984**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Simply one liner fix follow [this one](https://github.com/conda-forge/libtool-feedstock/pull/22)

### CODE REVIEW

**Comment by mingwandroid** [comment]
Should the build number not be -1000-ened?

**Comment by isuruf** [comment]
No, that's only when there's a new version.

**Comment by daizeng1984** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
