### PR TITLE
improve ignore_run_exports, don't refer to `-ng` packages

### PR DESCRIPTION
**Pull request by h-vetinari**
Xref https://github.com/conda-forge/ctng-compilers-feedstock/pull/148

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge/libtool, this should be good to go, PTAL! :)

**Comment by h-vetinari** [comment]
While I'm add it, I noticed today that libtool doesn't have a run-export. Should we add one?

**Comment by h-vetinari** [comment]
Ping @conda-forge/libtool

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
