### PR TITLE
Full path

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes https://github.com/conda-forge/libtool-feedstock/issues/18

### CODE REVIEW

**Review by chrisburr — APPROVED** [review]

**Comment by daizeng1984** [comment]
Thanks for quick update. My issue or most of others should be solved. However, FYI it still has hardcoded path for future TODO:
```
NM="/Users/runner/miniforge3/conda-bld/libtool_1598633134167/_build_env/bin/x86_64-apple-darwin13.4.0-nm" 
sys_lib_search_path_spec="/Users/runner/miniforge3/conda-bld/libtool_1598633134167/_build_env/lib/clang/10.0.1  /usr/local/lib"
LTCFLAGS="-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /xxx/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/libtool_1598633134167/work=/usr/local/src/conda/libtool-2.4.6 -fdebug-prefix-map=/xxx/lib/miniconda=/usr/local/src/conda-prefix"
```

**Comment by isuruf** [comment]
@daizeng1984, can you send a PR to fix the `NM` issue? Should be the same fix needed. We can ignore others for now.

**Comment by mingwandroid** [comment]
@isuruf, you might be interested in the new replacements stuff in conda-build 3.20.0

An example is: https://github.com/AnacondaRecipes/qt-feedstock/blob/master/recipe/conda_build_config.yaml#L9-L28

Would love to hear if it works (and fix it if not).

**Comment by mingwandroid** [comment]
The rg regex (if given) should necessarily broader than the regex_re. It is there to speed things up only.

**Pull request merged**
