### PR TITLE
Use the Jinja2 compiler syntax

### PR DESCRIPTION
**Pull request by leouieda**
I'm not sure this is adequate but I'm having trouble with incompatibilities with [gmt](https://github.com/conda-forge/gmt-feedstock) since the compiler updates. I noticed that [pcre](https://github.com/conda-forge/pcre-feedstock/blob/master/recipe/meta.yaml) isn't using the new compilers and this is a pcre dependency so I figured I'd start here.

### CODE REVIEW

**Comment by leouieda** [comment]
@jakirkham if this works and is acceptable, then #8 would be unnecessary.

**Comment by ocefpaf** [comment]
Ping @isuruf

**Comment by leouieda** [comment]
Yay, CIs are passing

**Comment by jakirkham** [comment]
LGTM. Thanks @leouieda :)

**Comment by leouieda** [comment]
@jakirkham I'm glad to help. Is this good to merge?

**Comment by leouieda** [comment]
The Circle build is failing now after the merge with a "Permission denied" while cloning the repo. Is there something wrong with the ssh key?

https://circleci.com/gh/conda-forge/libtool-feedstock/15

**Comment by ocefpaf** [comment]
I updated the token and re-started it.

**Comment by leouieda** [comment]
Perfect! Thank, Filipe

**Pull request merged**
